# -*- encoding: utf-8; mode: yaml -*-

# ========================================================================
# Copyright and other protections apply. Please see the accompanying
# ``LICENSE`` and ``CREDITS`` files for rights and restrictions governing
# use of this software. All rights not expressly waived or licensed are
# reserved. If those files are missing or appear to be modified from their
# originals, then please contact the author before viewing or using this
# software in any capacity.
# ========================================================================

sudo: false
language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"

install:
    - pip install coveralls tox-travis

matrix:
    allow_failures:
        # 3.6 is experimental (needs pylint >= 1.7.0)
        - python: "3.6"

        # PyPy3 is experimental
        - python: "pypy3"

script:
    - tox

after_success:
    - coveralls
